name: Django application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.4
          cache: "pip"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/local.txt', 'requirements/base.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements/local.txt

      - name: Build Docker
        run: docker compose build

      - name: Run Ruff (Docker)
        run: docker compose run django ruff check {{cookiecutter.project_slug}}/

      - name: Run MyPy (Docker)
        run: docker compose run django mypy --config mypy.ini {{cookiecutter.project_slug}}/

      - name: Run Tests (Docker)
        run: docker compose run django py.test

      - name: Run Ruff
        run: ruff check .

      - name: Type Check
        run: mypy --config mypy.ini {{cookiecutter.project_slug}}/

      - name: Run Tests
        run: pytest
